flappybird1:
  env_id: "FlappyBird-v0"
  num_episodes: 100000
  learning_rate: 0.0003
  network_sync_rate: 100
  num_hidden_1: 256
  num_hidden_2: 256
  d_model: 128
  d_ff: 512
  heads: 8
  dropout: 0.1
  N: 6
  seq_len: 16
  maxlen: 50000
  batch_size: 64
  discount_factor_g: 0.99