flappybird1:
  env_id: "FlappyBird-v0"
  num_episodes: 25
  learning_rate: 0.0003
  network_sync_rate: 100
  num_hidden_1: 256
  num_hidden_2: 256
  d_model: 128
  d_ff: 512
  heads: 8
  dropout: 0.1
  N: 8
  seq_len: 16
  maxlen: 200000
  batch_size: 1024
  discount_factor_g: 0.99